vulnerabilities:
  - id: CVE-2026-14257
    statement: Waiting for an updated npm version
    expired_at: 2027-01-01
  - id: CVE-2026-69192
    statement: Waiting for an updated npm version
    expired_at: 2027-01-01
  - id: CVE-2026-69152
    statement: Waiting for an updated npm version
    expired_at: 2027-01-01
