name: Release

on:
  push:
    tags:
      - v**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run ci
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
